services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PYTHONPATH=/app/src
    networks:
      - my-app-net
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/html:/usr/share/nginx/html
      - ./frontend/conf.d/:/etc/nginx/conf.d/ # Nginx configuration files to change the default port 80 to 3000:3000.
    networks:
      - my-app-net
  db:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: subHub
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-app-net

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    networks:
      - my-app-net

networks:
  my-app-net:
    driver: bridge

volumes:
  pgdata: